### ISSUE TITLE
Ipotenusa

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/RecuperoPython#10]
![es5_15](https://cloud.githubusercontent.com/assets/3002194/18488194/b257b84c-79f8-11e6-87d2-08a5b652e38a.png)

Creare la funzione hypotenuse all'interno di un modulo di nome mymath. Inserire vari test

**Comment by lucifero55** [comment]
Da quello che abbiamo fatto fino ad ora non abbiamo dichiarato il tipo di una variabile.
Funziona come per il c?

**Comment by FabioZTessitore** [comment]
dobbiamo ricominciare tutto da capo?

in python i tipi esistono (lancia l'interprete e chiedi type('abc') oppure type(1))
ma non è necessario dichiarare le variabili (l'interprete capisce di che tipo è dal valore che le assegni)

**Comment by lucifero55** [comment]
Vorrei testarli ma non mi dice i risultati che dovrebbero uscire :P

**Comment by FabioZTessitore** [comment]
il teorema di Pitagora non lo conosci?

**Comment by lucifero55** [comment]
l'ho scritto nel programma :P

**Comment by lucifero55** [comment]
Com'è?

**Comment by FabioZTessitore** [comment]
va bene però ti avevo chiesto di chiamare il modulo mymath e la funzione hypotenuse. Cerca di essere preciso sennò poi non ci troviamo
