### ISSUE TITLE
Corona Circolare

### ISSUE THREAD

**Issue by lucifero55** [lucifero55/RecuperoPython#11]

**Comment by FabioZTessitore** [comment]
calcola l'area di una corona circolare

suggerimento: creare prima una funzione per il calcolo dell'area di un cerchio

ps. metti tutte queste funzioni nel modulo mymath che NON hai ancora creato e non dimenticare i test

**Comment by lucifero55** [comment]
Così?

**Comment by lucifero55** [comment]
No non lo sapevo :P

**Comment by FabioZTessitore** [comment]
Secondo te perché ti ho fatto fare la funzione areaCerchio?

**Comment by lucifero55** [comment]
Ma le formule sono diverse :/

**Comment by FabioZTessitore** [comment]
non sia sciocco

**Comment by FabioZTessitore** [comment]
Ho inserito un commento in mymath.py

**Comment by FabioZTessitore** [comment]
ok, va bene
giusto per chiarire, non è che voglio essere pignolo. Quando tu crei la funzione AreaCerchio hai creato una black box (scatola nera) che sai cosa fa, ma non ti interessa come (astrazione). Una volta creata diventa un mattoncino del linguaggio. Inoltre la funzione AreaCoronaCircolare diventa molto più chiara. Addirittura uno che non sa cosa sia può impararlo leggendo il codice haha
