### ISSUE TITLE
Il ritorno di CAI

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/RecuperoPython#12]
Nella cartella CAI trovi una versione di CAI su cui hai lavorato in passato. Per cominciare trasforma il codice da C in Python

**Comment by lucifero55** [comment]
Ricordavo di averlo fatto più semplice ^^"

**Comment by FabioZTessitore** [comment]
e semplifica

**Comment by lucifero55** [comment]
Come si 'impotano' tutte le funzioni contenute in un file?

**Comment by FabioZTessitore** [comment]
meglio fare
```python
import nomefile

nomefile.nomefunzione
```

**Comment by FabioZTessitore** [comment]
problemi?

**Comment by lucifero55** [comment]
No, l'unico problema è il tempo.

Domanda: Le funzioni che richiamerebbero 'rand' in c, in python come diventano?

**Comment by FabioZTessitore** [comment]
In python esiste un modulo random già bello e fatto. Puoi dare un'occhiata da terminale:
```bash
$ python
>>> import random
>>> dir(random)
```

**Comment by lucifero55** [comment]
Bisogna utilizzare un sostituto di 'srand(time(NULL))' per generare numeri casuali?

**Comment by FabioZTessitore** [comment]
provo ad indovinare.
Hai scritto un piccolo programmino in Python che estrae e stampa dieci numeri interi. Lo hai lanciato più volte e non sei riuscito a scoprire se vengono estratti sempre gli stessi numeri o se sono diversi. Ho indovinato?

**Comment by lucifero55** [comment]
nono nulla del genere ^^"

**Comment by lucifero55** [comment]
Non so perchè quando devo prendere un programma e convertirlo in un altro linguaggio mi passa proprio la voglia. 
Fa lo stesso se lo faccio da capo in python? 
(Ai fini di apprendimento)

**Comment by FabioZTessitore** [comment]
Riscrivere significa rifare. I linguaggi sono diversi

Il lunedì 19 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
https://github.com/shockone/black-screen Mi spiegate come installare questo programma?

**Comment by lucifero55** [comment]
while(N!=3 && A!=3){
}
Come diventa in python?

**Comment by FabioZTessitore** [comment]
ma perché fai queste domande?
cosa non sai fare? il ciclo while? la &&? cosa?

**Comment by lucifero55** [comment]
&&

**Comment by FabioZTessitore** [comment]
and

Il giovedì 22 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Come si ritorna una stringa?

**Comment by FabioZTessitore** [comment]
Come sempre
return stringa

Il giovedì 22 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
![problema123](https://cloud.githubusercontent.com/assets/16176113/18747737/1f82f792-80cf-11e6-96d2-4bd704fca755.png)

Come faccio a stampare il tutto come si deve?

**Comment by FabioZTessitore** [comment]
Quando fai a="hajshd", 61, ecc stai memorizzando non una stringa ma una
tupla. Devi fare "hajshd" + str(61) + ecc

Il giovedì 22 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Perchè si crea cai.pyc?

**Comment by FabioZTessitore** [comment]
Lo crea l'interprete per evitare di interpretare ogni volta. È un codice
facilmente eseguibile dall'interprete, ma non è codice oggetto (ci vuole
comunque l'interprete per l'esecuzione). In questo modo si evita di
processare il file di testo che è un'operazione relativamente lenta

Il giovedì 22 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Inoltre è portatile, non dipende dalla macchina

Il giovedì 22 settembre 2016, Fabio Z Tessitore <fabioztessitore@gmail.com>
ha scritto:

**Comment by lucifero55** [comment]
Va bene o devo aggiungere altro?

**Comment by FabioZTessitore** [comment]
non capisco perché nel modulo cai hai messo una funzione random_between

**Comment by lucifero55** [comment]
per la lettura del codice, risulta facile capire cosa fa

**Comment by FabioZTessitore** [comment]
ma tu avevi un modulo cai che dovevi solo copiare

**Comment by lucifero55** [comment]
Non ho capito

**Comment by FabioZTessitore** [comment]
la funzione random_between faceva parte del modulo random.
Il modulo random in python esiste già e mette a disposizione le funzioni randint e randrange (meglio quest'ultima) per estrarre un numero compreso in un intervallo

il modulo cai aveva lo scopo di fornire al main tutte le funzionalità necessarie al suo funzionamento.
in particolare serve una funzione che estrae un numero ad una cifra che avevamo chiamato estraiCifra

**Comment by lucifero55** [comment]
Credevo voleste che main potesse attingere SOLO a cai per funzionare.

**Comment by FabioZTessitore** [comment]
appunto. per questo in cai ci vuole la funzione estraiCifra

**Comment by lucifero55** [comment]
Così?

**Comment by FabioZTessitore** [comment]
hai solo cambiato il nome. Secondo te una funzione che si chiama estraiCifra richiede parametri per poter funzionare?

**Comment by lucifero55** [comment]
Ok ora ho capito

**Comment by FabioZTessitore** [comment]
ok, va bene però devi mettere randrange e non randint
randint include gli estremi, quindi estrae anche 10 nel tuo codice
randrange invece si comporta come tutte le funzioni python (randrange(0, 10) estrae tra 0 e 9 compresi)
