### ISSUE TITLE
Linguaggio

### ISSUE THREAD

**Issue by lucifero55** [lucifero55/RecuperoPython#13]
Quest'anno scolastico ci sarà uno studio approfondito dei Database e con loro i linguaggi JavaScript e php. 
Mi domandavo se voi aveste delle esercitazioni sull'html e sul php.

**Comment by FabioZTessitore** [comment]
era previsto più in la. Poi vediamo come fare per conciliare

**Comment by lucifero55** [comment]
![dubbi](https://cloud.githubusercontent.com/assets/16176113/18685977/8936dc90-7f7a-11e6-8b10-c066c9c3695d.png)

**Comment by lucifero55** [comment]
Capito l'errore, era nei 2 punti che andavano sostituiti con un uguale. 
Però attendo comunque una risposta per la differenza tra i 2 metodi

**Comment by FabioZTessitore** [comment]
`class="Ita"`
tu hai messo i due punti invece dell'uguale

**Comment by FabioZTessitore** [comment]
id serve ad identificare un elemento. Solo un elemento nella pagina può avere un certo id. Ad esempio se una cella diventa id="ita", non puoi usare "ita" per nessun altro id.
class invece crea una categoria e puoi avere tutti gli elementi che vuoi appartenenti ad una certa categoria

**Comment by lucifero55** [comment]
Per quanto banale almeno è scritto bene? :/
Ricevuto il commento lo cancellerò u.u
