### ISSUE TITLE
livello 2

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/RecuperoPython#14]
![es5_44](https://cloud.githubusercontent.com/assets/3002194/18806921/1b091bf2-823b-11e6-8720-521bd45e1bb8.png)

**Comment by lucifero55** [comment]
Come si fa un in python ad utilizzare 'case'

**Comment by lucifero55** [comment]
Ho fatto la scelta di far rimanere il main semplice e incasinarmi il lavoro nel cai.py

Non capisco il motivo della stampa di "None" quando viene richiesta la soluzione

**Comment by FabioZTessitore** [comment]
switch case non esiste in python

**Comment by FabioZTessitore** [comment]
la funzione Question NON ritorna una stringa, ma la stampa con print.
Nel main hai scritto invece `print Question(...)'

**Comment by FabioZTessitore** [comment]
ti veniva chista una cosa più semplice, lavorare con numeri a una cifra o a due cifre, NON con un numero qualsiasi di cifre

**Comment by lucifero55** [comment]
Non ho ancora capito perchè esce 'None'

**Comment by FabioZTessitore** [comment]
la funzione Question NON ritorna una stringa, ma la stampa con print.
Nel main hai scritto invece print Question(...)

**Comment by lucifero55** [comment]
Ok chiaro ^^
Ma sto facendo bene o sto facendo una mostruosità mai vista prima?

**Comment by FabioZTessitore** [comment]
stai facendo bene

**Comment by lucifero55** [comment]
print "Decidi tra:\n1 Somma\n2 Sottrazione\n3 Divisione\n4 Moltiplicazione" 

Come faccio a tornare a capo dopo '\n'?

**Comment by FabioZTessitore** [comment]
```python
print "bla bla bla\n" \
           "bla bla bla"
```

**Comment by FabioZTessitore** [comment]
Manca l'opzione 5

**Comment by FabioZTessitore** [comment]
la logica di Question non va bene. Praticamente ti affidi al caso per stampare la riga giusta

**Comment by lucifero55** [comment]
'Question()' funziona a seconda della risposta esatta, che nel main dichiarata prima.

**Comment by FabioZTessitore** [comment]
**è possibile stabilire con certezza quale operazione è stata effettuata a partire dalla risposta**

**Comment by lucifero55** [comment]
aspetto illuminazione ^^"

**Comment by FabioZTessitore** [comment]
si si aspetta

**Comment by lucifero55** [comment]
Aspetto

**Comment by FabioZTessitore** [comment]
aspetta aspetta ...

**Comment by lucifero55** [comment]
Mi serve un suggerimento xD

**Comment by FabioZTessitore** [comment]
Question, così come Risposta_Esatta dipende dall'operazione, non dal risultato

**Comment by lucifero55** [comment]
Risposta esatta va bene o va modificata anche quella?

**Comment by FabioZTessitore** [comment]
non proprio. La scelta dell'operando in questa funzione ti crea problemi (infatti per esempio non sai come stampare la domanda)

**Comment by lucifero55** [comment]
Mi sono bloccato. Mi serve una mano

**Comment by FabioZTessitore** [comment]
pseudocodice è corretto, dovresti cercare di scrivere il codice così come avevi intenzione di fare e non così come hai fatto haha

il problema sta nella scelta dell'operando. finché è un numero compreso tra 1 e 4 sai come fare. Se l'utente immette 5 ti perdi.

**Comment by lucifero55** [comment]
Mi sembra che lo pseudocodice sia come main.py.
Quando l'utente immette 5 non so come far scegliere una delle altre opzioni e se ci riesco, come farla coincidere con il calcolo della risposta esatta.

**Comment by FabioZTessitore** [comment]
### nota 1
quello che chiami `operando` in realtà è l'`operatore`

### nota 2
pseudocodice e main non sono uguali, non hai ancora corretto i parametri della funzione `domanda`

### nota 3
quando l'utente sceglie un numero compreso tra 1 e 4 l'operatore è fisso e sai come gestirlo.

quando sceglie 5, l'operatore ad ogni problema deve cambiare. di conseguenza domanda e risposta vanno scelte coerentemente

**Comment by lucifero55** [comment]
Nota 1 Colpa della mia ignoranza
Nota 2 Credevo mi aver rimesso le cose a posto 
Note 3 Questo l'ho capito, la domanda è 'come farlo', non 'cosa fare'

**Comment by FabioZTessitore** [comment]
### extra
quando vuoi lasciare una if (o while o altro) senza un blocco puoi usare `pass`
```python
if nonSoCosaFare:
    pass
```

### nota 3
immagina questo dialogo tra il computer (tu) e un utente:
- cosa vuoi fare?
+ tutte le operazioni
- estraggo il primo numero
- estraggo il secondo numero
- faccio un'operazione a caso tra + - * /
- non so farti la domanda perché non so che operazione ho fatto
+ ma allora sei un computer Windows! ti spengo

**Comment by lucifero55** [comment]
Si può creare una variabile comune tra due funzioni?

**Comment by FabioZTessitore** [comment]
Le regole per variabili e funzioni le conosci

Il mercoledì 28 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Mi verrebbe in mente di salvare il valore generato in maniera casuale da Question() e di riproporlo in Risposta_Esatta

**Comment by FabioZTessitore** [comment]
Ti verrebbe o ti viene?

Il mercoledì 28 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Mi viene. Ma allora non conosco le regole per variabili e funzioni.
Per una funzione esiste solo ciò che prende in entrata.
Dovrei aggiungere un parametro a Risposta_Esatta()?

**Comment by lucifero55** [comment]
Mi aiuti a capire. 
Voglio continuare a programmare.

**Comment by FabioZTessitore** [comment]
Lo stai facendo per migliorare le capacità di ragionamento. Quindi ragiona.
Cerca di capire cosa dovrebbe fare ogni funzione e di cosa ha bisogno.

Il mercoledì 28 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Ora come ora funziona.
Cosa non va bene

**Comment by lucifero55** [comment]
Si ricordi di guardare il codice

**Comment by FabioZTessitore** [comment]
diciamo che va bene. Ti ho mandato la mia versione per confronto.
Le peculiarità sono due: usa una chiamata ricorsiva quando l'operazione è la 5 e ritorna due variabili in una tupla.
