### ISSUE TITLE
Nuova distro, vecchi problemi.

### ISSUE THREAD

**Issue by lucifero55** [lucifero55/RecuperoPython#15]
Sono passato a Debian.
![problema](https://cloud.githubusercontent.com/assets/16176113/18855704/246824ec-8455-11e6-967b-81590d9724d4.png)

Colore di file, cartelle ecc.
Grazie per l'aiuto ^^"

**Comment by FabioZTessitore** [comment]
Impostazioni del profilo

Il martedì 27 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:
