### ISSUE TITLE
Ciclo for

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/RecuperoPython#3]
Apri il terminale, lancia l'interprete python e fai qualche prova con `range()`
```bash
$ python
>>> range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> range(1, 10, 3)
[1, 4, 7]
>>> range(5, 0, -1)
[5, 4, 3, 2, 1]
```

In countdown_for.py trovi un esempio di ciclo for (usato in congiunzione con range)

**Comment by lucifero55** [comment]
fatto
