### ISSUE TITLE
Twice

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/RecuperoPython#5]
guarda il file twice.py
trovi un tipo di funzione che in C non puoi scrivere. Infatti il parametro `elem` può essere di qualsiasi tipo

**Comment by lucifero55** [comment]
Quindi invece di chiamare il tipo potrei sempre usare elem?

**Comment by FabioZTessitore** [comment]
ma che diavolo significa "chiamare il tipo"?

**Comment by lucifero55** [comment]
Giusto. In python non si fa.
Chiaro

**Comment by FabioZTessitore** [comment]
Mah. Forse volevi dire "dichiarare il tipo"
