### ISSUE TITLE
Distanza

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/RecuperoPython#7]
creare una funzione che calcola la distanza tra due punti del piano

**Comment by lucifero55** [comment]
in python un ipotetico "num++" non funziona?

**Comment by FabioZTessitore** [comment]
no. Non l'hanno voluto

**Comment by lucifero55** [comment]
Una alternativa?

**Comment by lucifero55** [comment]
num=num+1?

**Comment by FabioZTessitore** [comment]
num = num + 1 è preferito
in alternativa num +=  1 che non è molto amato

**Comment by FabioZTessitore** [comment]
l'esercizio richiede la distanza tra punti del piano, non la differenza tra due numeri

**Comment by lucifero55** [comment]
tipo
Punto a(1,2)
Punto b(4,4)

**Comment by FabioZTessitore** [comment]
si ma visto che Punto non ce l'hai, usa solo le coordinate

**Comment by lucifero55** [comment]
Come faccio la radice?

**Comment by FabioZTessitore** [comment]
## 1)
```python
import math
...
math.sqrt()
```

## 2)
```python
numero**0.5
```

**Comment by lucifero55** [comment]
Potrebbe darmi una ipotetica distanza tra 2 punti così da poter controllare se funziona?

**Comment by FabioZTessitore** [comment]
(3, 0) e (0, 4) -> 5.0
(3, 1) e (1, 4) -> 5.0

**Comment by lucifero55** [comment]
Com'è?

**Comment by FabioZTessitore** [comment]
ok

l'elevazione a potenza si fa con **
quindi potevi usarla per fare i quadrati (num1x-nu2x)**2

invece elevare a 1/2 cioè 0.5 è un altro modo per scrivere la radice (ah la matematica!)
