### ISSUE TITLE
test di distance

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/RecuperoPython#9]
vedi distance1.py per un esempio di codice per il test della funzione (inclusa in un file separato per creare un modulo)

**Comment by lucifero55** [comment]
Meglio essere ordinati che fare tutto assieme :P 
Chiaro

**Comment by FabioZTessitore** [comment]
in distance2.py puoi vedere come integrare i test all'interno della funzione stessa. In questo modo ogni funzione ha tutto al suo interno, anche i test per controllarla
